
import { PuzzleBlockData } from '@/components/PuzzleBlock';

export const DATA_STRUCTURE_ARRAY_PUZZLE = {
  blocks: [
    { id: 'block1', content: 'const fruits = ["apple", "banana", "orange"]', type: 'variable' as const, isPlaced: false },
    { id: 'block2', content: 'fruits.push("grape")', type: 'code' as const, isPlaced: false },
    { id: 'block3', content: 'fruits.unshift("kiwi")', type: 'code' as const, isPlaced: false },
    { id: 'block4', content: 'const lastFruit = fruits.pop()', type: 'code' as const, isPlaced: false },
    { id: 'block5', content: 'const firstFruit = fruits.shift()', type: 'code' as const, isPlaced: false },
    { id: 'block6', content: 'console.log(fruits)', type: 'code' as const, isPlaced: false },
    { id: 'block7', content: 'console.log(`Removed first: ${firstFruit}, last: ${lastFruit}`)', type: 'code' as const, isPlaced: false },
  ],
  solution: ['block1', 'block2', 'block3', 'block4', 'block5', 'block6', 'block7'],
  hint: "Use push/pop methods to add/remove elements from the end, unshift/shift for the beginning",
  description: "Learn about array operations in JavaScript",
  expectedOutput: `["apple", "banana"]\nRemoved first: kiwi, last: grape`
};

export const DATA_STRUCTURE_OBJECT_PUZZLE = {
  blocks: [
    { id: 'block1', content: 'const user = {', type: 'variable' as const, isPlaced: false },
    { id: 'block2', content: '  name: "Alice",', type: 'code' as const, isPlaced: false },
    { id: 'block3', content: '  age: 25', type: 'code' as const, isPlaced: false },
    { id: 'block4', content: '}', type: 'code' as const, isPlaced: false },
    { id: 'block5', content: 'user.email = "alice@example.com"', type: 'code' as const, isPlaced: false },
    { id: 'block6', content: 'console.log(Object.keys(user))', type: 'code' as const, isPlaced: false },
    { id: 'block7', content: 'console.log(Object.values(user))', type: 'code' as const, isPlaced: false },
    { id: 'block8', content: 'const { name, age } = user', type: 'code' as const, isPlaced: false },
    { id: 'block9', content: 'console.log(`${name} is ${age} years old`)', type: 'code' as const, isPlaced: false },
  ],
  solution: ['block1', 'block2', 'block3', 'block4', 'block5', 'block6', 'block7', 'block8', 'block9'],
  hint: "Create an object, add properties, and use object destructuring",
  description: "Learn about object manipulation in JavaScript",
  expectedOutput: `["name", "age", "email"]\n["Alice", 25, "alice@example.com"]\nAlice is 25 years old`
};

export const BINARY_TREE_PUZZLE = {
  blocks: [
    { id: 'block1', content: 'class Node {', type: 'code' as const, isPlaced: false },
    { id: 'block2', content: '  constructor(value) {', type: 'code' as const, isPlaced: false },
    { id: 'block3', content: '    this.value = value', type: 'code' as const, isPlaced: false },
    { id: 'block4', content: '    this.left = null', type: 'code' as const, isPlaced: false },
    { id: 'block5', content: '    this.right = null', type: 'code' as const, isPlaced: false },
    { id: 'block6', content: '  }', type: 'code' as const, isPlaced: false },
    { id: 'block7', content: '}', type: 'code' as const, isPlaced: false },
    { id: 'block8', content: 'function inOrderTraversal(node) {', type: 'function' as const, isPlaced: false },
    { id: 'block9', content: '  if (node === null) return', type: 'code' as const, isPlaced: false },
    { id: 'block10', content: '  inOrderTraversal(node.left)', type: 'code' as const, isPlaced: false },
    { id: 'block11', content: '  console.log(node.value)', type: 'code' as const, isPlaced: false },
    { id: 'block12', content: '  inOrderTraversal(node.right)', type: 'code' as const, isPlaced: false },
    { id: 'block13', content: '}', type: 'code' as const, isPlaced: false },
    { id: 'block14', content: 'const root = new Node(10)', type: 'code' as const, isPlaced: false },
    { id: 'block15', content: 'root.left = new Node(5)', type: 'code' as const, isPlaced: false },
    { id: 'block16', content: 'root.right = new Node(15)', type: 'code' as const, isPlaced: false },
    { id: 'block17', content: 'inOrderTraversal(root)', type: 'code' as const, isPlaced: false },
  ],
  solution: ['block1', 'block2', 'block3', 'block4', 'block5', 'block6', 'block7', 'block8', 'block9', 'block10', 'block11', 'block12', 'block13', 'block14', 'block15', 'block16', 'block17'],
  hint: "Create a binary tree and implement in-order traversal",
  description: "Learn about binary trees and traversal algorithms",
  expectedOutput: `5\n10\n15`
};

export const LINKED_LIST_PUZZLE = {
  blocks: [
    { id: 'block1', content: 'class Node {', type: 'code' as const, isPlaced: false },
    { id: 'block2', content: '  constructor(value) {', type: 'code' as const, isPlaced: false },
    { id: 'block3', content: '    this.value = value', type: 'code' as const, isPlaced: false },
    { id: 'block4', content: '    this.next = null', type: 'code' as const, isPlaced: false },
    { id: 'block5', content: '  }', type: 'code' as const, isPlaced: false },
    { id: 'block6', content: '}', type: 'code' as const, isPlaced: false },
    { id: 'block7', content: 'class LinkedList {', type: 'code' as const, isPlaced: false },
    { id: 'block8', content: '  constructor() {', type: 'code' as const, isPlaced: false },
    { id: 'block9', content: '    this.head = null', type: 'code' as const, isPlaced: false },
    { id: 'block10', content: '  }', type: 'code' as const, isPlaced: false },
    { id: 'block11', content: '  append(value) {', type: 'function' as const, isPlaced: false },
    { id: 'block12', content: '    const newNode = new Node(value)', type: 'code' as const, isPlaced: false },
    { id: 'block13', content: '    if (!this.head) {', type: 'control' as const, isPlaced: false },
    { id: 'block14', content: '      this.head = newNode', type: 'code' as const, isPlaced: false },
    { id: 'block15', content: '      return', type: 'code' as const, isPlaced: false },
    { id: 'block16', content: '    }', type: 'code' as const, isPlaced: false },
    { id: 'block17', content: '    let current = this.head', type: 'code' as const, isPlaced: false },
    { id: 'block18', content: '    while (current.next) {', type: 'control' as const, isPlaced: false },
    { id: 'block19', content: '      current = current.next', type: 'code' as const, isPlaced: false },
    { id: 'block20', content: '    }', type: 'code' as const, isPlaced: false },
    { id: 'block21', content: '    current.next = newNode', type: 'code' as const, isPlaced: false },
    { id: 'block22', content: '  }', type: 'code' as const, isPlaced: false },
    { id: 'block23', content: '  printList() {', type: 'function' as const, isPlaced: false },
    { id: 'block24', content: '    let current = this.head', type: 'code' as const, isPlaced: false },
    { id: 'block25', content: '    const values = []', type: 'code' as const, isPlaced: false },
    { id: 'block26', content: '    while (current) {', type: 'control' as const, isPlaced: false },
    { id: 'block27', content: '      values.push(current.value)', type: 'code' as const, isPlaced: false },
    { id: 'block28', content: '      current = current.next', type: 'code' as const, isPlaced: false },
    { id: 'block29', content: '    }', type: 'code' as const, isPlaced: false },
    { id: 'block30', content: '    console.log(values.join(" -> "))', type: 'code' as const, isPlaced: false },
    { id: 'block31', content: '  }', type: 'code' as const, isPlaced: false },
    { id: 'block32', content: '}', type: 'code' as const, isPlaced: false },
    { id: 'block33', content: 'const list = new LinkedList()', type: 'code' as const, isPlaced: false },
    { id: 'block34', content: 'list.append("A")', type: 'code' as const, isPlaced: false },
    { id: 'block35', content: 'list.append("B")', type: 'code' as const, isPlaced: false },
    { id: 'block36', content: 'list.append("C")', type: 'code' as const, isPlaced: false },
    { id: 'block37', content: 'list.printList()', type: 'code' as const, isPlaced: false },
  ],
  solution: ['block1', 'block2', 'block3', 'block4', 'block5', 'block6', 'block7', 'block8', 'block9', 'block10', 'block11', 'block12', 'block13', 'block14', 'block15', 'block16', 'block17', 'block18', 'block19', 'block20', 'block21', 'block22', 'block23', 'block24', 'block25', 'block26', 'block27', 'block28', 'block29', 'block30', 'block31', 'block32', 'block33', 'block34', 'block35', 'block36', 'block37'],
  hint: "Create a linked list with append and print methods",
  description: "Learn about linked list data structure implementation",
  expectedOutput: `A -> B -> C`
};

export const HASH_TABLE_PUZZLE = {
  blocks: [
    { id: 'block1', content: 'class HashTable {', type: 'code' as const, isPlaced: false },
    { id: 'block2', content: '  constructor(size = 10) {', type: 'code' as const, isPlaced: false },
    { id: 'block3', content: '    this.buckets = new Array(size)', type: 'code' as const, isPlaced: false },
    { id: 'block4', content: '  }', type: 'code' as const, isPlaced: false },
    { id: 'block5', content: '  hash(key) {', type: 'function' as const, isPlaced: false },
    { id: 'block6', content: '    let total = 0', type: 'code' as const, isPlaced: false },
    { id: 'block7', content: '    for (let i = 0; i < key.length; i++) {', type: 'control' as const, isPlaced: false },
    { id: 'block8', content: '      total += key.charCodeAt(i)', type: 'code' as const, isPlaced: false },
    { id: 'block9', content: '    }', type: 'code' as const, isPlaced: false },
    { id: 'block10', content: '    return total % this.buckets.length', type: 'code' as const, isPlaced: false },
    { id: 'block11', content: '  }', type: 'code' as const, isPlaced: false },
    { id: 'block12', content: '  set(key, value) {', type: 'function' as const, isPlaced: false },
    { id: 'block13', content: '    const index = this.hash(key)', type: 'code' as const, isPlaced: false },
    { id: 'block14', content: '    if (!this.buckets[index]) {', type: 'control' as const, isPlaced: false },
    { id: 'block15', content: '      this.buckets[index] = []', type: 'code' as const, isPlaced: false },
    { id: 'block16', content: '    }', type: 'code' as const, isPlaced: false },
    { id: 'block17', content: '    this.buckets[index].push([key, value])', type: 'code' as const, isPlaced: false },
    { id: 'block18', content: '  }', type: 'code' as const, isPlaced: false },
    { id: 'block19', content: '  get(key) {', type: 'function' as const, isPlaced: false },
    { id: 'block20', content: '    const index = this.hash(key)', type: 'code' as const, isPlaced: false },
    { id: 'block21', content: '    if (!this.buckets[index]) return null', type: 'code' as const, isPlaced: false },
    { id: 'block22', content: '    for (const [k, v] of this.buckets[index]) {', type: 'control' as const, isPlaced: false },
    { id: 'block23', content: '      if (k === key) return v', type: 'code' as const, isPlaced: false },
    { id: 'block24', content: '    }', type: 'code' as const, isPlaced: false },
    { id: 'block25', content: '    return null', type: 'code' as const, isPlaced: false },
    { id: 'block26', content: '  }', type: 'code' as const, isPlaced: false },
    { id: 'block27', content: '}', type: 'code' as const, isPlaced: false },
    { id: 'block28', content: 'const ht = new HashTable()', type: 'code' as const, isPlaced: false },
    { id: 'block29', content: 'ht.set("name", "Alice")', type: 'code' as const, isPlaced: false },
    { id: 'block30', content: 'ht.set("age", 25)', type: 'code' as const, isPlaced: false },
    { id: 'block31', content: 'console.log(ht.get("name"))', type: 'code' as const, isPlaced: false },
    { id: 'block32', content: 'console.log(ht.get("age"))', type: 'code' as const, isPlaced: false },
  ],
  solution: ['block1', 'block2', 'block3', 'block4', 'block5', 'block6', 'block7', 'block8', 'block9', 'block10', 'block11', 'block12', 'block13', 'block14', 'block15', 'block16', 'block17', 'block18', 'block19', 'block20', 'block21', 'block22', 'block23', 'block24', 'block25', 'block26', 'block27', 'block28', 'block29', 'block30', 'block31', 'block32'],
  hint: "Implement a hash table with hash function, set, and get methods",
  description: "Learn about hash tables and hash functions",
  expectedOutput: `Alice\n25`
};
