// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwanzqvzxgxsfmqtsbfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3YW56cXZ6eGd4c2ZtcXRzYmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODkzNDksImV4cCI6MjA1OTk2NTM0OX0.K1KFbU_J7xfJw8V-qq6nBud40UbEgI-rJZzAH7-_VP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});